apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - gke-rdma-nic-template.yaml

openapi:
  path: disaggregatedset-schema.json

patches:
  - patch: |-
      apiVersion: disaggregatedset.x-k8s.io/v1
      kind: DisaggregatedSet
      metadata:
        name: wide-ep-nvidia-gpu-vllm
      spec:
        roles:
          - name: prefill
            spec:
              leaderWorkerTemplate:
                workerTemplate:
                  spec: &gke-common
                    affinity:
                      podAffinity:
                        preferredDuringSchedulingIgnoredDuringExecution:
                          - weight: 2
                            podAffinityTerm:
                              labelSelector:
                                matchLabels:
                                  llm-d.ai/role: prefill
                              matchLabelKeys:
                                - component
                              topologyKey: cloud.google.com/gce-topology-block
                          - weight: 1
                            podAffinityTerm:
                              labelSelector:
                                matchLabels:
                                  llm-d.ai/role: prefill
                              matchLabelKeys:
                                - component
                              topologyKey: cloud.google.com/gce-topology-subblock
                    tolerations:
                      - key: nvidia.com/gpu
                        operator: Exists
                        effect: NoSchedule
                      - key: sandbox.gke.io/runtime
                        operator: Exists
                        effect: NoSchedule
                    resourceClaims:
                      - name: gke-rdma-claim-0
                        resourceClaimTemplateName: gke-rdma-nic-template
                      - name: gke-rdma-claim-1
                        resourceClaimTemplateName: gke-rdma-nic-template
                      - name: gke-rdma-claim-2
                        resourceClaimTemplateName: gke-rdma-nic-template
                      - name: gke-rdma-claim-3
                        resourceClaimTemplateName: gke-rdma-nic-template
                      - name: gke-rdma-claim-4
                        resourceClaimTemplateName: gke-rdma-nic-template
                      - name: gke-rdma-claim-5
                        resourceClaimTemplateName: gke-rdma-nic-template
                      - name: gke-rdma-claim-6
                        resourceClaimTemplateName: gke-rdma-nic-template
                      - name: gke-rdma-claim-7
                        resourceClaimTemplateName: gke-rdma-nic-template
                    containers:
                      - name: vllm
                        securityContext:
                          privileged: true
                        resources:
                          claims:
                            - name: gke-rdma-claim-0
                            - name: gke-rdma-claim-1
                            - name: gke-rdma-claim-2
                            - name: gke-rdma-claim-3
                            - name: gke-rdma-claim-4
                            - name: gke-rdma-claim-5
                            - name: gke-rdma-claim-6
                            - name: gke-rdma-claim-7
                        env:
                          - name: NCCL_TUNER_PLUGIN
                            value: "none"
                          - name: NCCL_NET_PLUGIN
                            value: ""
                          - name: UCX_IB_ROCE_REACHABILITY_MODE
                            value: "all"
                          - name: DEEP_EP_DEVICE_TO_HCA_MAPPING
                            value: "0:mlx5_0:1,1:mlx5_1:1,2:mlx5_2:1,3:mlx5_3:1,4:mlx5_4:1,5:mlx5_5:1,6:mlx5_6:1,7:mlx5_7:1"
                          - name: NVSHMEM_DISABLED_GDRCOPY
                            value: "true"
                          - name: HF_HUB_DOWNLOAD_TIMEOUT
                            value: "60"
                          - name: HF_HUB_DISABLE_XET
                            value: "1"
                    volumes:
                      - name: hf-cache
                        emptyDir: null
                        hostPath:
                          path: /mnt/stateful_partition/kube-ephemeral-ssd/shared_disk/vllm-hf-cache/
                          type: DirectoryOrCreate
                      - name: jit-cache
                        emptyDir: null
                        hostPath:
                          path: /mnt/stateful_partition/kube-ephemeral-ssd/shared_disk/vllm-jit-cache/
                          type: DirectoryOrCreate
          - name: decode
            spec:
              leaderWorkerTemplate:
                workerTemplate:
                  spec:
                    <<: *gke-common
                    affinity:
                      podAffinity:
                        preferredDuringSchedulingIgnoredDuringExecution:
                          - weight: 2
                            podAffinityTerm:
                              labelSelector:
                                matchLabels:
                                  llm-d.ai/role: decode
                              matchLabelKeys:
                                - component
                              topologyKey: cloud.google.com/gce-topology-block
                          - weight: 1
                            podAffinityTerm:
                              labelSelector:
                                matchLabels:
                                  llm-d.ai/role: decode
                              matchLabelKeys:
                                - component
                              topologyKey: cloud.google.com/gce-topology-subblock
